name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: script
        shell: bash
        run: |
            git clone "https://github.com/jabrena/jbang-ci-example"
            cd jbang-ci-example
            curl -Ls https://sh.jbang.dev | bash -s - app setup
            ~/.jbang/bin/jbang .github/OASValidator.java